---
- name: Install Apache2 on agent1
  hosts: apache
  become: true
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: true
    - name: Start apache2
      service:
        name: apache2
        state: started
        enabled: true

- name: Install Nginx on agent2
  hosts: nginx
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: true
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: true
